# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]

jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
       contents: read
       packages: write
     steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up JDK 11.0.2
       uses: actions/setup-java@v1
       with:
         java-version: 11.0.2
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     - name: Teste Jfrog
       uses: jfrog/setup-jfrog-cli@v2
       env:
         JF_ENV_1: ${{ secrets.JF_SECRET_ENV }}
     - run: |
         jf rt ping --url https://odinartifactory.jfrog.io --user svc_devops --access-token eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJydjg5V2M5eU5UVnJOMDE4NHVLMUpua2xiWm42SVRsVHRQT3pZTWF5dkNJIn0.eyJleHQiOiJ7XCJyZXZvY2FibGVcIjpcInRydWVcIn0iLCJzdWIiOiJqZmFjQDAxZnhqc2djZWpxc3pjMDF4YndjZ3YxdGQ2XC91c2Vyc1wvc3ZjX2Rldm9wcyIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnNcL3VzZXIiLCJhdWQiOiIqQCoiLCJpc3MiOiJqZmZlQDAwMCIsImV4cCI6MTY4MTIzODE4MiwiaWF0IjoxNjQ5NzAyMTgyLCJqdGkiOiJlOGY4Y2VhNy03ODRmLTRjNWItYTM3Ny05NjkyZDgxZGJlYWQifQ.C2gAvaoSCbEAzYv3qKvgImFFM3co1NB87Ls7D3xvI5-xw6AdCax0DW2SuRxx1iiEuZvrE99HSVI0Mg3RBktzhCIiPDdAcQMq3qtlhKLokkYwcdGJubozv_ClChZNzLTphTaZn1I4nNpwh9Uig4SWsx3eerSCc_KJwWJ-zzRgtiRaZuIQ615VZw9DHSN6tKKjcIsn9Xmm1FOH-8YA8bBKd_c-tmEJCuEn3vJbqWay4eKPLeBAQVJpORPkYGSaJc4nbU20Fj0oLgDufK_p3sn81G78g3ann4zouemmAYTTXOIerT7wHtI9guftaVhgF26iDkAFpxOGt_LxKAGwbH_O6A
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

#     - name: Publish to GitHub Packages Apache Maven
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
